"""add_tabela_preco_and_vinculo_venda

Revision ID: 009
Revises: 008
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009'
down_revision = '008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tabelas_preco',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=255), nullable=False),
        sa.Column('descricao', sa.String(length=255), nullable=True),
        sa.Column('margem_geral_percentual', sa.Numeric(10, 2), nullable=False, server_default='0'),
        sa.Column('ativa', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tabelas_preco_nome'), 'tabelas_preco', ['nome'], unique=False)

    op.create_table(
        'tabela_preco_itens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tabela_preco_id', sa.Integer(), nullable=False),
        sa.Column('produto_id', sa.Integer(), nullable=False),
        sa.Column('margem_especifica_percentual', sa.Numeric(10, 2), nullable=False, server_default='0'),
        sa.Column('preco_calculado', sa.Numeric(10, 2), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['tabela_preco_id'], ['tabelas_preco.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tabela_preco_id', 'produto_id', name='uq_tabela_preco_produto')
    )
    op.create_index(op.f('ix_tabela_preco_itens_tabela_preco_id'), 'tabela_preco_itens', ['tabela_preco_id'], unique=False)
    op.create_index(op.f('ix_tabela_preco_itens_produto_id'), 'tabela_preco_itens', ['produto_id'], unique=False)

    op.add_column('vendas', sa.Column('tabela_preco_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_vendas_tabela_preco_id'), 'vendas', ['tabela_preco_id'], unique=False)
    op.create_foreign_key(
        op.f('fk_vendas_tabela_preco_id_tabelas_preco'),
        'vendas',
        'tabelas_preco',
        ['tabela_preco_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_vendas_tabela_preco_id_tabelas_preco'), 'vendas', type_='foreignkey')
    op.drop_index(op.f('ix_vendas_tabela_preco_id'), table_name='vendas')
    op.drop_column('vendas', 'tabela_preco_id')

    op.drop_index(op.f('ix_tabela_preco_itens_produto_id'), table_name='tabela_preco_itens')
    op.drop_index(op.f('ix_tabela_preco_itens_tabela_preco_id'), table_name='tabela_preco_itens')
    op.drop_table('tabela_preco_itens')

    op.drop_index(op.f('ix_tabelas_preco_nome'), table_name='tabelas_preco')
    op.drop_table('tabelas_preco')
    # ### end Alembic commands ###
